spring:
  profiles:
    active: test
    
    
    
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: test-dev
    
---
server:
  port: 8002
spring:
  profiles: test
  application: test-test
